server:
  port: 7000

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${SYHTHEMS_EUREKA_HOSTNAME:eureka.syhthems.local}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
