server:
  port: 8080

spring:
  profiles:
    active:
      - common
      - db
      - web
      - sso
      - device

syhthems:
  security:
    sso-server: http://localhost:8080/sso

logging:
  level:
    org.springframework.security: debug